version: "2"

services:
    y2redis:
      image: phpdockerio/redis:latest
      container_name: y2redis
      networks:
        - backend

    y2mysql:
      image: mysql:5.7
      container_name: y2mysql
      environment:
        - MYSQL_ROOT_PASSWORD=superpassword
        - MYSQL_DATABASE=dbyvv
        - MYSQL_USER=vladimir
        - MYSQL_PASSWORD=superpwd
      volumes:
        - ./mysql/data:/var/lib/mysql
      networks:
        - backend

    y2phpfpm:
      build: ./php-fpm
      #dockerfile: php-fpm/Dockerfile
      container_name: y2phpfpm
      volumes:
        - ./app:/var/www/dy2
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./php-fpm/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini
      #links:
      #  - dy2-mysql
      #  - dy2-redis
      networks:
        - backend

    y2nginx:
      image: phpdockerio/nginx:latest
      container_name: y2nginx
      volumes:
          - .:/var/www/dy2
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      expose:
       - "9001"
      depends_on:
        - y2phpfpm
      #links:
      # - dy2-php-fpm
      networks:
        - backend
        
    chrome:
        container_name: chrome
        image: selenium/standalone-chrome-debug:3.7.1
        ports:
          - 4444
          - 5900
        networks:
            - backend

networks:
  backend:
    driver: bridge
    #external: true
