version: "3.7"

services:
    yii2redis:
        build: ./docker/redis
        container_name: yii2redis
        hostname: redis
        restart: always
        ports:
          - 6379:6379
        networks:
          - backend

    yii2mysql:
        build: ./docker/mysql
        privileged: true
        container_name: yii2mysql
        hostname: mysql
        image: mysql_dev
        ports:
            - "3306:3306"
        networks:
          - backend

    yii2phpfpm:
        build: ./docker/php-fpm
        #dockerfile: php-fpm/Dockerfile
        container_name: yii2phpfpm
        hostname: phpfpm
        restart: always
        volumes:
          - ./app:/var/www/dy2:rw
          - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
          - ./docker/php-fpm/xdebug.ini:/etc/php/7.1/mods-available/xdebug.ini
        #links:
        #  - dy2-mysql
        #  - dy2-redis
        networks:
          - backend

    yii2nginx:
        build: ./docker/nginx
        container_name: yii2nginx
        hostname: nginx
        volumes:
            - ./app:/var/www/dy2:rw
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "8080:80"
        expose:
        - "9009"
        depends_on:
          - yii2phpfpm
        #links:
        # - dy2-php-fpm
        networks:
          - backend
        
    chrome:
        container_name: chrome
        image: selenium/standalone-chrome-debug:3.7.1
        ports:
          - 4444
          - 5900
        networks:
            - backend

networks:
  backend:
    driver: bridge
    #external: true
